import {
  IAspect,
  aws_elasticloadbalancingv2 as elbv2,
  aws_cloudwatch as cloudwatch,
  Duration,
} from 'aws-cdk-lib';
import { Construct, IConstruct } from 'constructs';
import { AlarmBaseProps, validateTotalAlarmPeriod } from './common';

/**
 * The recommended metrics for ApplicationLoadBalancer alarms.
 */
export enum ApplicationLoadBalancerRecommendedAlarmsMetrics {
  /**
   * The number of connection requests that were rejected because the load balancer had reached its maximum connections.
   */
  REJECTED_CONNECTION_COUNT = 'RejectedConnectionCount',
  /**
   * The number of HTTP 4XX client error codes generated by the load balancer.
   */
  HTTP_CODE_ELB_4XX_COUNT = 'HTTPCode_ELB_4XX_Count',
  /**
   * The number of HTTP 5XX server error codes generated by the load balancer.
   */
  HTTP_CODE_ELB_5XX_COUNT = 'HTTPCode_ELB_5XX_Count',
  /**
   * The number of HTTP 5XX server error codes generated by the targets.
   */
  HTTP_CODE_TARGET_5XX_COUNT = 'HTTPCode_Target_5XX_Count',
}

/**
 * The common optional configuration for the alarms.
 */
export interface ApplicationLoadBalancerAlarmBaseConfig extends AlarmBaseProps {
  /**
   * The period over which the specified statistic is applied.
   *
   * @default Duration.minutes(1)
   */
  readonly period?: Duration;
}

/**
 * The common properties for the ApplicationLoadBalancer alarms.
 */
export interface ApplicationLoadBalancerAlarmProps {
  /**
   * The ApplicationLoadBalancer to monitor.
   */
  readonly loadBalancer: elbv2.ApplicationLoadBalancer;
}

/**
 * Configuration for the RejectedConnectionCount alarm.
 */
export interface ApplicationLoadBalancerRejectedConnectionCountAlarmConfig extends ApplicationLoadBalancerAlarmBaseConfig {
  /**
   * The value against which the specified statistic is compared.
   * You should set this threshold based on the acceptable number of rejected connections.
   *
   * @default 0
   */
  readonly threshold?: number;
  /**
   * The number of periods over which data is compared to the specified threshold.
   *
   * @default 3
   */
  readonly evaluationPeriods?: number;
  /**
   * The number of data points that must be breaching to trigger the alarm.
   *
   * @default 3
   */
  readonly datapointsToAlarm?: number;
  /**
   * The alarm name.
   *
   * @default - loadBalancerName + ' - RejectedConnectionCount'
   */
  readonly alarmName?: string;
  /**
   * The description of the alarm.
   *
   * @default - This alarm is used to detect when the load balancer is rejecting connections.
   * Rejected connections can indicate that the load balancer has reached its maximum connection limit.
   */
  readonly alarmDescription?: string;
}

/**
 * The properties for the ApplicationLoadBalancerRejectedConnectionCountAlarm construct.
 */
export interface ApplicationLoadBalancerRejectedConnectionCountAlarmProps extends
  ApplicationLoadBalancerAlarmProps, ApplicationLoadBalancerRejectedConnectionCountAlarmConfig {}

/**
 * This alarm is used to detect when the load balancer is rejecting connections.
 *
 * Rejected connections can indicate that the load balancer has reached its maximum connection limit.
 *
 * The alarm is triggered when the number of rejected connections is greater than threshold.
 */
export class ApplicationLoadBalancerRejectedConnectionCountAlarm extends cloudwatch.Alarm {
  constructor(scope: IConstruct, id: string, props: ApplicationLoadBalancerRejectedConnectionCountAlarmProps) {
    const alarmName = props.alarmName ?? `${props.loadBalancer.loadBalancerName} - ${ApplicationLoadBalancerRecommendedAlarmsMetrics.REJECTED_CONNECTION_COUNT}`;
    const period = props.period ?? Duration.minutes(1);
    const evaluationPeriods = props.evaluationPeriods ?? 3;
    const datapointsToAlarm = props.datapointsToAlarm ?? 3;
    const threshold = props.threshold ?? 0;
    const treatMissingData = props.treatMissingData ?? cloudwatch.TreatMissingData.MISSING;
    const alarmDescription = props.alarmDescription ?? 'This alarm is used to detect when the load balancer is rejecting connections.'
      + ' Rejected connections can indicate that the load balancer has reached its maximum connection limit.';

    validateTotalAlarmPeriod(period, evaluationPeriods, alarmName);

    super(scope, id, {
      alarmName,
      metric: new cloudwatch.Metric({
        namespace: 'AWS/ApplicationELB',
        metricName: ApplicationLoadBalancerRecommendedAlarmsMetrics.REJECTED_CONNECTION_COUNT,
        dimensionsMap: {
          LoadBalancer: props.loadBalancer.loadBalancerFullName,
        },
        statistic: 'Sum',
        period,
      }),
      threshold,
      evaluationPeriods,
      datapointsToAlarm,
      treatMissingData,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      alarmDescription,
    });

    if (props.alarmAction) this.addAlarmAction(props.alarmAction);
    if (props.okAction) this.addOkAction(props.okAction);
    if (props.insufficientDataAction) this.addInsufficientDataAction(props.insufficientDataAction);
  }
}

/**
 * Configuration for the HTTPCode_ELB_4XX_Count alarm.
 */
export interface ApplicationLoadBalancerHttpCode4xxCountAlarmConfig extends
  ApplicationLoadBalancerAlarmBaseConfig {
  /**
   * The value against which the specified statistic is compared.
   * You should set this threshold based on the acceptable number of 4XX errors.
   *
   * @default 0
   */
  readonly threshold?: number;
  /**
   * The number of periods over which data is compared to the specified threshold.
   *
   * @default 3
   */
  readonly evaluationPeriods?: number;
  /**
   * The number of data points that must be breaching to trigger the alarm.
   *
   * @default 3
   */
  readonly datapointsToAlarm?: number;
  /**
   * The alarm name.
   *
   * @default - loadBalancerName + ' - HTTPCode_ELB_4XX_Count'
   */
  readonly alarmName?: string;
  /**
   * The description of the alarm.
   *
   * @default - This alarm is used to detect when the load balancer is generating 4XX errors.
   * A high number of 4XX errors can indicate client-side issues or misconfigured requests.
   */
  readonly alarmDescription?: string;
}

/**
 * The properties for the ApplicationLoadBalancerHttpCode4xxCountAlarm construct.
 */
export interface ApplicationLoadBalancerHttpCode4xxCountAlarmProps extends
  ApplicationLoadBalancerAlarmProps, ApplicationLoadBalancerHttpCode4xxCountAlarmConfig {}

/**
 * This alarm is used to detect when the load balancer is generating 4XX errors.
 *
 * A high number of 4XX errors can indicate client-side issues or misconfigured requests.
 *
 * The alarm is triggered when the number of 4XX errors is greater than threshold.
 */
export class ApplicationLoadBalancerHttpCode4xxCountAlarm extends cloudwatch.Alarm {
  constructor(scope: IConstruct, id: string, props: ApplicationLoadBalancerHttpCode4xxCountAlarmProps) {
    const alarmName = props.alarmName ?? `${props.loadBalancer.loadBalancerName} - ${ApplicationLoadBalancerRecommendedAlarmsMetrics.HTTP_CODE_ELB_4XX_COUNT}`;
    const period = props.period ?? Duration.minutes(1);
    const evaluationPeriods = props.evaluationPeriods ?? 3;
    const datapointsToAlarm = props.datapointsToAlarm ?? 3;
    const threshold = props.threshold ?? 0;
    const treatMissingData = props.treatMissingData ?? cloudwatch.TreatMissingData.MISSING;
    const alarmDescription = props.alarmDescription ?? 'This alarm is used to detect when the load balancer is generating 4XX errors.'
      + ' A high number of 4XX errors can indicate client-side issues or misconfigured requests.';

    validateTotalAlarmPeriod(period, evaluationPeriods, alarmName);

    super(scope, id, {
      alarmName,
      metric: new cloudwatch.Metric({
        namespace: 'AWS/ApplicationELB',
        metricName: ApplicationLoadBalancerRecommendedAlarmsMetrics.HTTP_CODE_ELB_4XX_COUNT,
        dimensionsMap: {
          LoadBalancer: props.loadBalancer.loadBalancerFullName,
        },
        statistic: 'Sum',
        period,
      }),
      threshold,
      evaluationPeriods,
      datapointsToAlarm,
      treatMissingData,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      alarmDescription,
    });

    if (props.alarmAction) this.addAlarmAction(props.alarmAction);
    if (props.okAction) this.addOkAction(props.okAction);
    if (props.insufficientDataAction) this.addInsufficientDataAction(props.insufficientDataAction);
  }
}

/**
 * Configuration for the HTTPCode_ELB_5XX_Count alarm.
 */
export interface ApplicationLoadBalancerHttpCode5xxCountAlarmConfig extends ApplicationLoadBalancerAlarmBaseConfig {
  /**
   * The value against which the specified statistic is compared.
   * You should set this threshold based on the acceptable number of 5XX errors.
   *
   * @default 0
   */
  readonly threshold?: number;
  /**
   * The number of periods over which data is compared to the specified threshold.
   *
   * @default 3
   */
  readonly evaluationPeriods?: number;
  /**
   * The number of data points that must be breaching to trigger the alarm.
   *
   * @default 3
   */
  readonly datapointsToAlarm?: number;
  /**
   * The alarm name.
   *
   * @default - loadBalancerName + ' - HTTPCode_ELB_5XX_Count'
   */
  readonly alarmName?: string;
  /**
   * The description of the alarm.
   *
   * @default - This alarm is used to detect when the load balancer is generating 5XX errors.
   * A high number of 5XX errors can indicate issues with the load balancer itself.
   */
  readonly alarmDescription?: string;
}

/**
 * The properties for the ApplicationLoadBalancerHttpCode5xxCountAlarm construct.
 */
export interface ApplicationLoadBalancerHttpCode5xxCountAlarmProps extends
  ApplicationLoadBalancerAlarmProps, ApplicationLoadBalancerHttpCode5xxCountAlarmConfig {}

/**
 * This alarm is used to detect when the load balancer is generating 5XX errors.
 *
 * A high number of 5XX errors can indicate issues with the load balancer itself.
 *
 * The alarm is triggered when the number of 5XX errors is greater than threshold.
 */
export class ApplicationLoadBalancerHttpCode5xxCountAlarm extends cloudwatch.Alarm {
  constructor(scope: IConstruct, id: string, props: ApplicationLoadBalancerHttpCode5xxCountAlarmProps) {
    const alarmName = props.alarmName ?? `${props.loadBalancer.loadBalancerName} - ${ApplicationLoadBalancerRecommendedAlarmsMetrics.HTTP_CODE_ELB_5XX_COUNT}`;
    const period = props.period ?? Duration.minutes(1);
    const evaluationPeriods = props.evaluationPeriods ?? 3;
    const datapointsToAlarm = props.datapointsToAlarm ?? 3;
    const threshold = props.threshold ?? 0;
    const treatMissingData = props.treatMissingData ?? cloudwatch.TreatMissingData.MISSING;
    const alarmDescription = props.alarmDescription ?? 'This alarm is used to detect when the load balancer is generating 5XX errors.'
      + ' A high number of 5XX errors can indicate issues with the load balancer itself.';

    validateTotalAlarmPeriod(period, evaluationPeriods, alarmName);

    super(scope, id, {
      alarmName,
      metric: new cloudwatch.Metric({
        namespace: 'AWS/ApplicationELB',
        metricName: ApplicationLoadBalancerRecommendedAlarmsMetrics.HTTP_CODE_ELB_5XX_COUNT,
        dimensionsMap: {
          LoadBalancer: props.loadBalancer.loadBalancerFullName,
        },
        statistic: 'Sum',
        period,
      }),
      threshold,
      evaluationPeriods,
      datapointsToAlarm,
      treatMissingData,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      alarmDescription,
    });

    if (props.alarmAction) this.addAlarmAction(props.alarmAction);
    if (props.okAction) this.addOkAction(props.okAction);
    if (props.insufficientDataAction) this.addInsufficientDataAction(props.insufficientDataAction);
  }
}

/**
 * Configuration for the HTTPCode_Target_5XX_Count alarm.
 */
export interface ApplicationLoadBalancerHttpCodeTarget5xxCountAlarmConfig extends ApplicationLoadBalancerAlarmBaseConfig {
  /**
   * The value against which the specified statistic is compared.
   * You should set this threshold based on the acceptable number of 5XX errors from targets.
   *
   * @default 0
   */
  readonly threshold?: number;
  /**
   * The number of periods over which data is compared to the specified threshold.
   *
   * @default 3
   */
  readonly evaluationPeriods?: number;
  /**
   * The number of data points that must be breaching to trigger the alarm.
   *
   * @default 3
   */
  readonly datapointsToAlarm?: number;
  /**
   * The alarm name.
   *
   * @default - loadBalancerName + ' - HTTPCode_Target_5XX_Count'
   */
  readonly alarmName?: string;
  /**
   * The description of the alarm.
   *
   * @default - This alarm is used to detect when the targets are generating 5XX errors.
   * A high number of 5XX errors can indicate issues with the application or backend services.
   */
  readonly alarmDescription?: string;
}

/**
 * The properties for the ApplicationLoadBalancerHttpCodeTarget5xxCountAlarm construct.
 */
export interface ApplicationLoadBalancerHttpCodeTarget5xxCountAlarmProps extends
  ApplicationLoadBalancerAlarmProps, ApplicationLoadBalancerHttpCodeTarget5xxCountAlarmConfig {}

/**
 * This alarm is used to detect when the targets are generating 5XX errors.
 *
 * A high number of 5XX errors can indicate issues with the application or backend services.
 *
 * The alarm is triggered when the number of 5XX errors from targets is greater than threshold.
 */
export class ApplicationLoadBalancerHttpCodeTarget5xxCountAlarm extends cloudwatch.Alarm {
  constructor(scope: IConstruct, id: string, props: ApplicationLoadBalancerHttpCodeTarget5xxCountAlarmProps) {
    const alarmName = props.alarmName ?? `${props.loadBalancer.loadBalancerName} - ${ApplicationLoadBalancerRecommendedAlarmsMetrics.HTTP_CODE_TARGET_5XX_COUNT}`;
    const period = props.period ?? Duration.minutes(1);
    const evaluationPeriods = props.evaluationPeriods ?? 3;
    const datapointsToAlarm = props.datapointsToAlarm ?? 3;
    const threshold = props.threshold ?? 0;
    const treatMissingData = props.treatMissingData ?? cloudwatch.TreatMissingData.MISSING;
    const alarmDescription = props.alarmDescription ?? 'This alarm is used to detect when the targets are generating 5XX errors.'
      + ' A high number of 5XX errors can indicate issues with the application or backend services.';

    validateTotalAlarmPeriod(period, evaluationPeriods, alarmName);

    super(scope, id, {
      alarmName,
      metric: new cloudwatch.Metric({
        namespace: 'AWS/ApplicationELB',
        metricName: ApplicationLoadBalancerRecommendedAlarmsMetrics.HTTP_CODE_TARGET_5XX_COUNT,
        dimensionsMap: {
          LoadBalancer: props.loadBalancer.loadBalancerFullName,
        },
        statistic: 'Sum',
        period,
      }),
      threshold,
      evaluationPeriods,
      datapointsToAlarm,
      treatMissingData,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      alarmDescription,
    });

    if (props.alarmAction) this.addAlarmAction(props.alarmAction);
    if (props.okAction) this.addOkAction(props.okAction);
    if (props.insufficientDataAction) this.addInsufficientDataAction(props.insufficientDataAction);
  }
}

/**
 * Configurations for the recommended alarms for an ApplicationLoadBalancer.
 *
 * Default actions are overridden by the actions specified in the
 * individual alarm configurations.
 */
export interface ApplicationLoadBalancerRecommendedAlarmsConfig {
  /**
   * The default action to take when an alarm is triggered.
   *
   * @default - None
   */
  readonly defaultAlarmAction?: cloudwatch.IAlarmAction;
  /**
   * The default action to take when an alarm enters the ok state.
   *
   * @default - None
   */
  readonly defaultOkAction?: cloudwatch.IAlarmAction;
  /**
   * The default action to take when an alarm has insufficient data.
   *
   * @default - None
   */
  readonly defaultInsufficientDataAction?: cloudwatch.IAlarmAction;
  /**
   * How to handle missing data for this alarm.
   *
   * @default TreatMissingData.MISSING
   */
  readonly treatMissingData?: cloudwatch.TreatMissingData;
  /**
   * Alarm metrics to exclude from the recommended alarms.
   *
   * @default - None
   */
  readonly excludeAlarms?: ApplicationLoadBalancerRecommendedAlarmsMetrics[];
  /**
   * The resources to exclude from the recommended alarms.
   *
   * Use a resources id to exclude a specific resource.
   */
  readonly excludeResources?: string[];
  /**
   * The configuration for the RejectedConnectionCount alarm.
   */
  readonly configRejectedConnectionCountAlarm?: ApplicationLoadBalancerRejectedConnectionCountAlarmConfig;
  /**
   * The configuration for the HTTPCode_ELB_4XX_Count alarm.
   */
  readonly configHttpCode4xxCountAlarm?: ApplicationLoadBalancerHttpCode4xxCountAlarmConfig;
  /**
   * The configuration for the HTTPCode_ELB_5XX_Count alarm.
   */
  readonly configHttpCode5xxCountAlarm?: ApplicationLoadBalancerHttpCode5xxCountAlarmConfig;
  /**
   * The configuration for the HTTPCode_Target_5XX_Count alarm.
   */
  readonly configHttpCodeTarget5xxCountAlarm?: ApplicationLoadBalancerHttpCodeTarget5xxCountAlarmConfig;
}

/**
 * Properties for the ApplicationLoadBalancerRecommendedAlarms construct.
 */
export interface ApplicationLoadBalancerRecommendedAlarmsProps extends ApplicationLoadBalancerRecommendedAlarmsConfig {
  /**
   * The ApplicationLoadBalancer to monitor.
   */
  readonly loadBalancer: elbv2.ApplicationLoadBalancer;
}

/**
 * A construct that creates the recommended alarms for an ApplicationLoadBalancer.
 *
 * @see https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html
 */
export class ApplicationLoadBalancerRecommendedAlarms extends Construct {
  /**
   * The RejectedConnectionCount alarm.
   */
  public readonly alarmRejectedConnectionCount?: ApplicationLoadBalancerRejectedConnectionCountAlarm;

  /**
   * The HTTPCode_ELB_4XX_Count alarm.
   */
  public readonly alarmHttpCode4xxCount?: ApplicationLoadBalancerHttpCode4xxCountAlarm;

  /**
   * The HTTPCode_ELB_5XX_Count alarm.
   */
  public readonly alarmHttpCode5xxCount?: ApplicationLoadBalancerHttpCode5xxCountAlarm;

  /**
   * The HTTPCode_Target_5XX_Count alarm.
   */
  public readonly alarmHttpCodeTarget5xxCount?: ApplicationLoadBalancerHttpCodeTarget5xxCountAlarm;

  constructor(scope: Construct, id: string, props: ApplicationLoadBalancerRecommendedAlarmsProps) {
    super(scope, id);

    if (!props.excludeAlarms?.includes(ApplicationLoadBalancerRecommendedAlarmsMetrics.REJECTED_CONNECTION_COUNT)) {
      this.alarmRejectedConnectionCount = new ApplicationLoadBalancerRejectedConnectionCountAlarm(this, `${props.loadBalancer.node.id}_RejectedConnectionCount`, {
        loadBalancer: props.loadBalancer,
        treatMissingData: props.treatMissingData,
        ...props.configRejectedConnectionCountAlarm,
      });

      if (props.defaultAlarmAction && !props.configRejectedConnectionCountAlarm?.alarmAction) {
        this.alarmRejectedConnectionCount.addAlarmAction(props.defaultAlarmAction);
      }

      if (props.defaultOkAction && !props.configRejectedConnectionCountAlarm?.okAction) {
        this.alarmRejectedConnectionCount.addOkAction(props.defaultOkAction);
      }

      if (props.defaultInsufficientDataAction && !props.configRejectedConnectionCountAlarm?.insufficientDataAction) {
        this.alarmRejectedConnectionCount.addInsufficientDataAction(props.defaultInsufficientDataAction);
      }
    }

    if (!props.excludeAlarms?.includes(ApplicationLoadBalancerRecommendedAlarmsMetrics.HTTP_CODE_ELB_4XX_COUNT)) {
      this.alarmHttpCode4xxCount = new ApplicationLoadBalancerHttpCode4xxCountAlarm(this, `${props.loadBalancer.node.id}_HttpCode4xxCount`, {
        loadBalancer: props.loadBalancer,
        treatMissingData: props.treatMissingData,
        ...props.configHttpCode4xxCountAlarm,
      });

      if (props.defaultAlarmAction && !props.configHttpCode4xxCountAlarm?.alarmAction) {
        this.alarmHttpCode4xxCount.addAlarmAction(props.defaultAlarmAction);
      }

      if (props.defaultOkAction && !props.configHttpCode4xxCountAlarm?.okAction) {
        this.alarmHttpCode4xxCount.addOkAction(props.defaultOkAction);
      }

      if (props.defaultInsufficientDataAction && !props.configHttpCode4xxCountAlarm?.insufficientDataAction) {
        this.alarmHttpCode4xxCount.addInsufficientDataAction(props.defaultInsufficientDataAction);
      }
    }

    if (!props.excludeAlarms?.includes(ApplicationLoadBalancerRecommendedAlarmsMetrics.HTTP_CODE_ELB_5XX_COUNT)) {
      this.alarmHttpCode5xxCount = new ApplicationLoadBalancerHttpCode5xxCountAlarm(this, `${props.loadBalancer.node.id}_HttpCode5xxCount`, {
        loadBalancer: props.loadBalancer,
        treatMissingData: props.treatMissingData,
        ...props.configHttpCode5xxCountAlarm,
      });

      if (props.defaultAlarmAction && !props.configHttpCode5xxCountAlarm?.alarmAction) {
        this.alarmHttpCode5xxCount.addAlarmAction(props.defaultAlarmAction);
      }

      if (props.defaultOkAction && !props.configHttpCode5xxCountAlarm?.okAction) {
        this.alarmHttpCode5xxCount.addOkAction(props.defaultOkAction);
      }

      if (props.defaultInsufficientDataAction && !props.configHttpCode5xxCountAlarm?.insufficientDataAction) {
        this.alarmHttpCode5xxCount.addInsufficientDataAction(props.defaultInsufficientDataAction);
      }
    }

    if (!props.excludeAlarms?.includes(ApplicationLoadBalancerRecommendedAlarmsMetrics.HTTP_CODE_TARGET_5XX_COUNT)) {
      this.alarmHttpCodeTarget5xxCount = new ApplicationLoadBalancerHttpCodeTarget5xxCountAlarm(this, `${props.loadBalancer.node.id}_HttpCodeTarget5xxCount`, {
        loadBalancer: props.loadBalancer,
        treatMissingData: props.treatMissingData,
        ...props.configHttpCodeTarget5xxCountAlarm,
      });

      if (props.defaultAlarmAction && !props.configHttpCodeTarget5xxCountAlarm?.alarmAction) {
        this.alarmHttpCodeTarget5xxCount.addAlarmAction(props.defaultAlarmAction);
      }

      if (props.defaultOkAction && !props.configHttpCodeTarget5xxCountAlarm?.okAction) {
        this.alarmHttpCodeTarget5xxCount.addOkAction(props.defaultOkAction);
      }

      if (props.defaultInsufficientDataAction && !props.configHttpCodeTarget5xxCountAlarm?.insufficientDataAction) {
        this.alarmHttpCodeTarget5xxCount.addInsufficientDataAction(props.defaultInsufficientDataAction);
      }
    }
  }
}

/**
 * An extension for the ApplicationLoadBalancer construct that provides methods
 * to create recommended alarms.
 */
export class ApplicationLoadBalancer extends elbv2.ApplicationLoadBalancer {
  constructor(scope: Construct, id: string, props: elbv2.ApplicationLoadBalancerProps) {
    super(scope, id, props);
  }

  /**
   * Creates an alarm that monitors the rejected connection count for the ApplicationLoadBalancer.
   */
  public alarmRejectedConnectionCount(props?: ApplicationLoadBalancerRejectedConnectionCountAlarmConfig):
  ApplicationLoadBalancerRejectedConnectionCountAlarm {
    return new ApplicationLoadBalancerRejectedConnectionCountAlarm(this, 'RejectedConnectionCountAlarm', {
      loadBalancer: this,
      ...props,
    });
  }

  /**
   * Creates an alarm that monitors the HTTP 4XX error count for the ApplicationLoadBalancer.
   */
  public alarmHttpCode4xxCount(props?: ApplicationLoadBalancerHttpCode4xxCountAlarmConfig): ApplicationLoadBalancerHttpCode4xxCountAlarm {
    return new ApplicationLoadBalancerHttpCode4xxCountAlarm(this, 'HttpCode4xxCountAlarm', {
      loadBalancer: this,
      ...props,
    });
  }

  /**
   * Creates an alarm that monitors the HTTP 5XX error count for the ApplicationLoadBalancer.
   */
  public alarmHttpCode5xxCount(props?: ApplicationLoadBalancerHttpCode5xxCountAlarmConfig): ApplicationLoadBalancerHttpCode5xxCountAlarm {
    return new ApplicationLoadBalancerHttpCode5xxCountAlarm(this, 'HttpCode5xxCountAlarm', {
      loadBalancer: this,
      ...props,
    });
  }

  /**
   * Creates an alarm that monitors the HTTP 5XX error count from targets for the ApplicationLoadBalancer.
   */
  public alarmHttpCodeTarget5xxCount(props?: ApplicationLoadBalancerHttpCodeTarget5xxCountAlarmConfig):
  ApplicationLoadBalancerHttpCodeTarget5xxCountAlarm {
    return new ApplicationLoadBalancerHttpCodeTarget5xxCountAlarm(this, 'HttpCodeTarget5xxCountAlarm', {
      loadBalancer: this,
      ...props,
    });
  }

  /**
   * Creates the recommended alarms for the ApplicationLoadBalancer.
   *
   * @see https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html
   */
  public applyRecommendedAlarms(props: ApplicationLoadBalancerRecommendedAlarmsConfig): ApplicationLoadBalancerRecommendedAlarms {
    return new ApplicationLoadBalancerRecommendedAlarms(this, 'ApplicationLoadBalancerRecommendedAlarms', {
      loadBalancer: this,
      ...props,
    });
  }
}

/**
 * Configures the recommended alarms for an ApplicationLoadBalancer.
 *
 * @see https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html
 */
export class ApplicationLoadBalancerRecommendedAlarmsAspect implements IAspect {
  constructor(private readonly props: ApplicationLoadBalancerRecommendedAlarmsConfig) {}

  public visit(node: IConstruct): void {
    if (node instanceof elbv2.ApplicationLoadBalancer) {
      if (this.props.excludeResources && this.props.excludeResources.includes(node.node.id)) {
        return;
      } else {
        const loadBalancer = node as elbv2.ApplicationLoadBalancer;

        new ApplicationLoadBalancerRecommendedAlarms(loadBalancer, 'ApplicationLoadBalancerRecommendedAlarmsFromAspect', {
          loadBalancer,
          ...this.props,
        });
      }
    }
  }
}