import {
  IAspect,
  aws_elasticloadbalancingv2 as elbv2,
  aws_cloudwatch as cloudwatch,
  Duration,
} from 'aws-cdk-lib';
import { Construct, IConstruct } from 'constructs';
import { AlarmBaseProps, validateTotalAlarmPeriod } from './common';

/**
 * The recommended metrics for NetworkLoadBalancer alarms.
 */
export enum NetworkLoadBalancerRecommendedAlarmsMetrics {
  /**
   * The number of reset (RST) packets sent from the load balancer.
   */
  TCP_ELB_RESET_COUNT = 'TcpElbResetCount',
  /**
   * The number of reset (RST) packets generated by the targets.
   */
  TCP_TARGET_RESET_COUNT = 'TcpTargetResetCount',
}

/**
 * The common optional configuration for the alarms.
 */
export interface NetworkLoadBalancerAlarmBaseConfig extends AlarmBaseProps {
  /**
   * The period over which the specified statistic is applied.
   *
   * @default Duration.minutes(1)
   */
  readonly period?: Duration;
}

/**
 * The common properties for the NetworkLoadBalancer alarms.
 */
export interface NetworkLoadBalancerAlarmProps {
  /**
   * The NetworkLoadBalancer to monitor.
   */
  readonly loadBalancer: elbv2.NetworkLoadBalancer;
}

/**
 * Configuration for the TcpElbResetCount alarm.
 */
export interface NetworkLoadBalancerTcpElbResetCountAlarmConfig extends NetworkLoadBalancerAlarmBaseConfig {
  /**
   * The value against which the specified statistic is compared.
   * You should set this threshold based on the acceptable number of TCP resets from the load balancer.
   *
   * @default 0
   */
  readonly threshold?: number;
  /**
   * The number of periods over which data is compared to the specified threshold.
   *
   * @default 3
   */
  readonly evaluationPeriods?: number;
  /**
   * The number of data points that must be breaching to trigger the alarm.
   *
   * @default 3
   */
  readonly datapointsToAlarm?: number;
  /**
   * The alarm name.
   *
   * @default - loadBalancerName + ' - TcpElbResetCount'
   */
  readonly alarmName?: string;
  /**
   * The description of the alarm.
   *
   * @default - This alarm is used to detect when the load balancer is sending TCP reset packets.
   * A high number of resets can indicate connectivity issues between the load balancer and clients.
   */
  readonly alarmDescription?: string;
}

/**
 * The properties for the NetworkLoadBalancerTcpElbResetCountAlarm construct.
 */
export interface NetworkLoadBalancerTcpElbResetCountAlarmProps extends
  NetworkLoadBalancerAlarmProps, NetworkLoadBalancerTcpElbResetCountAlarmConfig {}

/**
 * This alarm is used to detect when the load balancer is sending TCP reset packets.
 *
 * A high number of resets can indicate connectivity issues between the load balancer and clients.
 *
 * The alarm is triggered when the number of TCP resets from the load balancer is greater than threshold.
 */
export class NetworkLoadBalancerTcpElbResetCountAlarm extends cloudwatch.Alarm {
  constructor(scope: IConstruct, id: string, props: NetworkLoadBalancerTcpElbResetCountAlarmProps) {
    const alarmName = props.alarmName ?? `${props.loadBalancer.loadBalancerName} - ${NetworkLoadBalancerRecommendedAlarmsMetrics.TCP_ELB_RESET_COUNT}`;
    const period = props.period ?? Duration.minutes(1);
    const evaluationPeriods = props.evaluationPeriods ?? 3;
    const datapointsToAlarm = props.datapointsToAlarm ?? 3;
    const threshold = props.threshold ?? 0;
    const treatMissingData = props.treatMissingData ?? cloudwatch.TreatMissingData.MISSING;
    const alarmDescription = props.alarmDescription ?? 'This alarm is used to detect when the load balancer is sending TCP reset packets.'
      + ' A high number of resets can indicate connectivity issues between the load balancer and clients.';

    validateTotalAlarmPeriod(period, evaluationPeriods, alarmName);

    super(scope, id, {
      alarmName,
      metric: new cloudwatch.Metric({
        namespace: 'AWS/NetworkELB',
        metricName: NetworkLoadBalancerRecommendedAlarmsMetrics.TCP_ELB_RESET_COUNT,
        dimensionsMap: {
          LoadBalancer: props.loadBalancer.loadBalancerFullName,
        },
        statistic: 'Sum',
        period,
      }),
      threshold,
      evaluationPeriods,
      datapointsToAlarm,
      treatMissingData,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      alarmDescription,
    });

    if (props.alarmAction) this.addAlarmAction(props.alarmAction);
    if (props.okAction) this.addOkAction(props.okAction);
    if (props.insufficientDataAction) this.addInsufficientDataAction(props.insufficientDataAction);
  }
}

/**
 * Configuration for the TcpTargetResetCount alarm.
 */
export interface NetworkLoadBalancerTcpTargetResetCountAlarmConfig extends NetworkLoadBalancerAlarmBaseConfig {
  /**
   * The value against which the specified statistic is compared.
   * You should set this threshold based on the acceptable number of TCP resets from targets.
   *
   * @default 0
   */
  readonly threshold?: number;
  /**
   * The number of periods over which data is compared to the specified threshold.
   *
   * @default 3
   */
  readonly evaluationPeriods?: number;
  /**
   * The number of data points that must be breaching to trigger the alarm.
   *
   * @default 3
   */
  readonly datapointsToAlarm?: number;
  /**
   * The alarm name.
   *
   * @default - loadBalancerName + ' - TcpTargetResetCount'
   */
  readonly alarmName?: string;
  /**
   * The description of the alarm.
   *
   * @default - This alarm is used to detect when the targets are sending TCP reset packets.
   * A high number of resets can indicate connectivity issues between the load balancer and targets.
   */
  readonly alarmDescription?: string;
}

/**
 * The properties for the NetworkLoadBalancerTcpTargetResetCountAlarm construct.
 */
export interface NetworkLoadBalancerTcpTargetResetCountAlarmProps extends
  NetworkLoadBalancerAlarmProps, NetworkLoadBalancerTcpTargetResetCountAlarmConfig {}

/**
 * This alarm is used to detect when the targets are sending TCP reset packets.
 *
 * A high number of resets can indicate connectivity issues between the load balancer and targets.
 *
 * The alarm is triggered when the number of TCP resets from targets is greater than threshold.
 */
export class NetworkLoadBalancerTcpTargetResetCountAlarm extends cloudwatch.Alarm {
  constructor(scope: IConstruct, id: string, props: NetworkLoadBalancerTcpTargetResetCountAlarmProps) {
    const alarmName = props.alarmName ?? `${props.loadBalancer.loadBalancerName} - ${NetworkLoadBalancerRecommendedAlarmsMetrics.TCP_TARGET_RESET_COUNT}`;
    const period = props.period ?? Duration.minutes(1);
    const evaluationPeriods = props.evaluationPeriods ?? 3;
    const datapointsToAlarm = props.datapointsToAlarm ?? 3;
    const threshold = props.threshold ?? 0;
    const treatMissingData = props.treatMissingData ?? cloudwatch.TreatMissingData.MISSING;
    const alarmDescription = props.alarmDescription ?? 'This alarm is used to detect when the targets are sending TCP reset packets.'
      + ' A high number of resets can indicate connectivity issues between the load balancer and targets.';

    validateTotalAlarmPeriod(period, evaluationPeriods, alarmName);

    super(scope, id, {
      alarmName,
      metric: new cloudwatch.Metric({
        namespace: 'AWS/NetworkELB',
        metricName: NetworkLoadBalancerRecommendedAlarmsMetrics.TCP_TARGET_RESET_COUNT,
        dimensionsMap: {
          LoadBalancer: props.loadBalancer.loadBalancerFullName,
        },
        statistic: 'Sum',
        period,
      }),
      threshold,
      evaluationPeriods,
      datapointsToAlarm,
      treatMissingData,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
      alarmDescription,
    });

    if (props.alarmAction) this.addAlarmAction(props.alarmAction);
    if (props.okAction) this.addOkAction(props.okAction);
    if (props.insufficientDataAction) this.addInsufficientDataAction(props.insufficientDataAction);
  }
}

/**
 * Configurations for the recommended alarms for a NetworkLoadBalancer.
 *
 * Default actions are overridden by the actions specified in the
 * individual alarm configurations.
 */
export interface NetworkLoadBalancerRecommendedAlarmsConfig {
  /**
   * The default action to take when an alarm is triggered.
   *
   * @default - None
   */
  readonly defaultAlarmAction?: cloudwatch.IAlarmAction;
  /**
   * The default action to take when an alarm enters the ok state.
   *
   * @default - None
   */
  readonly defaultOkAction?: cloudwatch.IAlarmAction;
  /**
   * The default action to take when an alarm has insufficient data.
   *
   * @default - None
   */
  readonly defaultInsufficientDataAction?: cloudwatch.IAlarmAction;
  /**
   * How to handle missing data for this alarm.
   *
   * @default TreatMissingData.MISSING
   */
  readonly treatMissingData?: cloudwatch.TreatMissingData;
  /**
   * Alarm metrics to exclude from the recommended alarms.
   *
   * @default - None
   */
  readonly excludeAlarms?: NetworkLoadBalancerRecommendedAlarmsMetrics[];
  /**
   * The resources to exclude from the recommended alarms.
   *
   * Use a resources id to exclude a specific resource.
   */
  readonly excludeResources?: string[];
  /**
   * The configuration for the TcpElbResetCount alarm.
   */
  readonly configTcpElbResetCountAlarm?: NetworkLoadBalancerTcpElbResetCountAlarmConfig;
  /**
   * The configuration for the TcpTargetResetCount alarm.
   */
  readonly configTcpTargetResetCountAlarm?: NetworkLoadBalancerTcpTargetResetCountAlarmConfig;
}

/**
 * Properties for the NetworkLoadBalancerRecommendedAlarms construct.
 */
export interface NetworkLoadBalancerRecommendedAlarmsProps extends NetworkLoadBalancerRecommendedAlarmsConfig {
  /**
   * The NetworkLoadBalancer to monitor.
   */
  readonly loadBalancer: elbv2.NetworkLoadBalancer;
}

/**
 * A construct that creates the recommended alarms for a NetworkLoadBalancer.
 *
 * @see https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html
 */
export class NetworkLoadBalancerRecommendedAlarms extends Construct {
  /**
   * The TcpElbResetCount alarm.
   */
  public readonly alarmTcpElbResetCount?: NetworkLoadBalancerTcpElbResetCountAlarm;

  /**
   * The TcpTargetResetCount alarm.
   */
  public readonly alarmTcpTargetResetCount?: NetworkLoadBalancerTcpTargetResetCountAlarm;

  constructor(scope: Construct, id: string, props: NetworkLoadBalancerRecommendedAlarmsProps) {
    super(scope, id);

    if (!props.excludeAlarms?.includes(NetworkLoadBalancerRecommendedAlarmsMetrics.TCP_ELB_RESET_COUNT)) {
      this.alarmTcpElbResetCount = new NetworkLoadBalancerTcpElbResetCountAlarm(this, `${props.loadBalancer.node.id}_TcpElbResetCount`, {
        loadBalancer: props.loadBalancer,
        treatMissingData: props.treatMissingData,
        ...props.configTcpElbResetCountAlarm,
      });

      if (props.defaultAlarmAction && !props.configTcpElbResetCountAlarm?.alarmAction) {
        this.alarmTcpElbResetCount.addAlarmAction(props.defaultAlarmAction);
      }

      if (props.defaultOkAction && !props.configTcpElbResetCountAlarm?.okAction) {
        this.alarmTcpElbResetCount.addOkAction(props.defaultOkAction);
      }

      if (props.defaultInsufficientDataAction && !props.configTcpElbResetCountAlarm?.insufficientDataAction) {
        this.alarmTcpElbResetCount.addInsufficientDataAction(props.defaultInsufficientDataAction);
      }
    }

    if (!props.excludeAlarms?.includes(NetworkLoadBalancerRecommendedAlarmsMetrics.TCP_TARGET_RESET_COUNT)) {
      this.alarmTcpTargetResetCount = new NetworkLoadBalancerTcpTargetResetCountAlarm(this, `${props.loadBalancer.node.id}_TcpTargetResetCount`, {
        loadBalancer: props.loadBalancer,
        treatMissingData: props.treatMissingData,
        ...props.configTcpTargetResetCountAlarm,
      });

      if (props.defaultAlarmAction && !props.configTcpTargetResetCountAlarm?.alarmAction) {
        this.alarmTcpTargetResetCount.addAlarmAction(props.defaultAlarmAction);
      }

      if (props.defaultOkAction && !props.configTcpTargetResetCountAlarm?.okAction) {
        this.alarmTcpTargetResetCount.addOkAction(props.defaultOkAction);
      }

      if (props.defaultInsufficientDataAction && !props.configTcpTargetResetCountAlarm?.insufficientDataAction) {
        this.alarmTcpTargetResetCount.addInsufficientDataAction(props.defaultInsufficientDataAction);
      }
    }
  }
}

/**
 * An extension for the NetworkLoadBalancer construct that provides methods
 * to create recommended alarms.
 */
export class NetworkLoadBalancer extends elbv2.NetworkLoadBalancer {
  constructor(scope: Construct, id: string, props: elbv2.NetworkLoadBalancerProps) {
    super(scope, id, props);
  }

  /**
   * Creates an alarm that monitors the TCP reset count from the load balancer.
   */
  public alarmTcpElbResetCount(props?: NetworkLoadBalancerTcpElbResetCountAlarmConfig): NetworkLoadBalancerTcpElbResetCountAlarm {
    return new NetworkLoadBalancerTcpElbResetCountAlarm(this, 'TcpElbResetCountAlarm', {
      loadBalancer: this,
      ...props,
    });
  }

  /**
   * Creates an alarm that monitors the TCP reset count from targets.
   */
  public alarmTcpTargetResetCount(props?: NetworkLoadBalancerTcpTargetResetCountAlarmConfig): NetworkLoadBalancerTcpTargetResetCountAlarm {
    return new NetworkLoadBalancerTcpTargetResetCountAlarm(this, 'TcpTargetResetCountAlarm', {
      loadBalancer: this,
      ...props,
    });
  }

  /**
   * Creates the recommended alarms for the NetworkLoadBalancer.
   *
   * @see https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html
   */
  public applyRecommendedAlarms(props: NetworkLoadBalancerRecommendedAlarmsConfig): NetworkLoadBalancerRecommendedAlarms {
    return new NetworkLoadBalancerRecommendedAlarms(this, 'NetworkLoadBalancerRecommendedAlarms', {
      loadBalancer: this,
      ...props,
    });
  }
}

/**
 * Configures the recommended alarms for a NetworkLoadBalancer.
 *
 * @see https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html
 */
export class NetworkLoadBalancerRecommendedAlarmsAspect implements IAspect {
  constructor(private readonly props: NetworkLoadBalancerRecommendedAlarmsConfig) {}

  public visit(node: IConstruct): void {
    if (node instanceof elbv2.NetworkLoadBalancer) {
      if (this.props.excludeResources && this.props.excludeResources.includes(node.node.id)) {
        return;
      } else {
        const loadBalancer = node as elbv2.NetworkLoadBalancer;

        new NetworkLoadBalancerRecommendedAlarms(loadBalancer, 'NetworkLoadBalancerRecommendedAlarmsFromAspect', {
          loadBalancer,
          ...this.props,
        });
      }
    }
  }
}